import "./globals.css";

import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import { Footer } from "#/components/Footer";
import { RootLayout } from "#/components/RootLayout";
import { cn } from "#/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-gull">
      <body
        className={cn(
          "h-screen bg-blue2 font-sans antialiased flex flex-col",
          fontSans.variable
        )}
      >
        <RootLayout>{children}</RootLayout>
        <Footer
          githubLink="https://github.com/bleu-fi/composable-cow-hub"
          discordLink="https://discord.gg/cowprotocol"
        />
      </body>
    </html>
  );
}
